### ISSUE TITLE
Readme instructions do not work (missing dependencies)

### ISSUE THREAD

**Issue by cfcs** [talex5/qubes-mirage-skeleton#5]
The provided instructions do not work.

Consider changing
```
$ opam install mirage
```

to
```
$ opam install dns functoria-runtime lwt mirage-clock-freestanding mirage-logs mirage-net-xen mirage-qubes mirage-random mirage-runtime mirage-types mirage-types-lwt mirage-xen tcpip
```

or at least something that makes sure the required packages are installed (`opam install mirage-qubes dns`) ?

**Comment by talex5** [comment]
Does it work if you do `make depend`? I think this might have become necessary with Mirage 3...

**Comment by cfcs** [comment]
Sorry, I did get this to work back then :tada:
